import argparse
import openai  

client = openai.OpenAI()

def create_prompt(question):
    """Creates a prompt for text-to-SQL translation.
    
    Args:
    question: question to translate.
    
    Returns:
        SQL query translating question"""
    parts = []
    parts.append('Database')
    parts.append('create table Customers(customerID int, customerName text, City text);')
    parts.append('Translate this question to SQL:')
    parts.append(question)
    return '\n'.join(parts)


def call_llm(prompt):
    """Return answer generated by the LLM.
    
    Args: 
    prompt: prompt sent to LLM.
    
    Return:
        answer generated by LLM.
    """
    messages = [{'role':'user', 'content':prompt}]
    reply = client.chat.completions.create(
        model='gpt-4o', messages=messages['content']
        )
    return reply.choices[0].message.content


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('question', type=str, help='Question to translate')
    args = parser.parse_args()

    prompt = create_prompt(args.question)
    answer = call_llm(prompt)
    print(answer)


